#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

echo -e "Updating and installing Nginx.\n"
apt-get update -y
apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Creating new index
echo "Hello World!" > /var/www/html/index.html

# Starting nginx
service nginx start

echo -e "\n${green}Completed.${reset} ✅\n"
