#!/usr/bin/env bash
# A bash script that displays time for 12 hours and 59 minutes
counter1="0"
while [ "$counter1" -lt 13 ];do
	echo "Hour: $counter1"
	counter2="1"
	while [ "$counter2" -lt 60 ];do
		echo "$counter2"
		((counter2++))
	done
	((counter1++))
done
